name: flutterflip
description: Create your Flutter Apps visually!
version: 1.0.0-alpha.1

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  cupertino_icons: 1.0.6
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.0
  jaspr:
    git:
      url: https://github.com/FlipSuite/jaspr_flutterflip.git
      path: packages/jaspr
  jaspr_flutter_embed:
    git:
      url: https://github.com/FlipSuite/jaspr_flutterflip.git
      path: packages/jaspr_flutter_embed
  jaspr_riverpod:
    git:
      url: https://github.com/FlipSuite/jaspr_flutterflip.git
      path: packages/jaspr_riverpod
  js: ^0.6.7
  riverpod: ^2.4.0
  json_dynamic_widget: ^7.0.0+2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  jaspr_builder:
    git:
      url: https://github.com/FlipSuite/jaspr_flutterflip.git
      path: packages/jaspr_builder
  jaspr_tailwind: ^0.1.0
  jaspr_web_compilers: ^4.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/dash.png

jaspr:
  uses-ssr: true
  uses-flutter: true
